# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/horizon-core"
    schedule:
      interval: "weekly"
    reviewers: 
      - telekom/pubsub-horizon
  - package-ecosystem: "gradle"
    directory: "/horizon-spring-boot-autoconfigure"
    schedule:
      interval: "weekly"
    reviewers: 
      - telekom/pubsub-horizon
  - package-ecosystem: "gradle"
    directory: "/horizon-spring-boot-starter"
    schedule:
      interval: "weekly"
    reviewers: 
      - telekom/pubsub-horizon
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers: 
      - telekom/pubsub-horizon
