package de.telekom.eni.pandora.horizon.model.db;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

import java.io.PrintWriter;
import java.io.StringWriter;

@Getter
@Setter(AccessLevel.PRIVATE)
@JsonInclude(JsonInclude.Include.NON_NULL)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor
@Builder(access = AccessLevel.PRIVATE)
public class StateError {
    private String message;
    private String type;
    private String stackTrace;

    public static StateError fromException(Exception ex) {
        return builder().message(ex.getMessage())
                        .type(ex.getClass().getName())
                        .stackTrace(getStackTrace(ex))
                        .build();
    }

    /**
     * <p>Gets the stack trace from a Throwable as a String.</p>
     *
     * <p>The result of this method vary by JDK version as this method
     * uses {@link Throwable#printStackTrace(java.io.PrintWriter)}.
     * On JDK1.3 and earlier, the cause exception will not be shown
     * unless the specified throwable alters printStackTrace.</p>
     *
     * @param throwable  the {@code Throwable} to be examined
     * @return the stack trace as generated by the exception's
     *  {@code printStackTrace(PrintWriter)} method
     */
    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }


}
