# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Gradle Publish Snapshot
on:
  workflow_run:
    workflows:
      - "Gradle Build and Test"
    types:
      - completed
    branches-ignore:
      - 'main'
      - 'master'
      - 'develop'
jobs:
  gradle-publish:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:25-dind

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle publish
        env:
          PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
          PUBLISH_GPG_PRIVATE_KEY: ${{ secrets.PUBLISH_GPG_PRIVATE_KEY }}
          PUBLISH_GPG_PASSPHRASE: ${{ secrets.PUBLISH_GPG_PASSPHRASE }}
        run: ./gradlew -Pversion=0.0.0-${{github.GITHUB_REF_NAME}}-SNAPSHOT publish
