# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Gradle Build and Test
on:
  push:
  pull_request:
    branches:
      - main
      - develop
jobs:
  gradle:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:25-dind

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80
        if: github.event_name == 'pull_request'
      - name: Execute Gradle snapshot publish
        if: ${{ github.event_name != 'pull_request' }}
        env:
          PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
          PUBLISH_GPG_PRIVATE_KEY: ${{ secrets.PUBLISH_GPG_PRIVATE_KEY }}
          PUBLISH_GPG_PASSPHRASE: ${{ secrets.PUBLISH_GPG_PASSPHRASE }}
        run: |
          export LOWERCASE_BRANCH=${GITHUB_REF_NAME,,}
          export CLEAN_BRANCH=$(echo $LOWERCASE_BRANCH | sed 's/_/-/g; s/\//-/g; s/+/-/g; s/\./-/g')
          ./gradlew -Pversion=0.0.0-${CLEAN_BRANCH}-SNAPSHOT publish